# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicApp(object):
    def setupUi(self, MusicApp):
        MusicApp.setObjectName("MusicApp")
        MusicApp.resize(880, 550)
        MusicApp.setMinimumSize(QtCore.QSize(880, 550))
        MusicApp.setMaximumSize(QtCore.QSize(880, 550))
        self.centralwidget = QtWidgets.QWidget(MusicApp)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, -10, 881, 561))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/img/utils/images/bg_0012_3.png"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.overlay_layer = QtWidgets.QLabel(self.centralwidget)
        self.overlay_layer.setGeometry(QtCore.QRect(0, 0, 881, 551))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.overlay_layer.setFont(font)
        self.overlay_layer.setText("")
        self.overlay_layer.setPixmap(QtGui.QPixmap(":/img/utils/bg_imgs/bg_overlay.png"))
        self.overlay_layer.setScaledContents(True)
        self.overlay_layer.setObjectName("overlay_layer")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setGeometry(QtCore.QRect(0, 0, 881, 51))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.App_logo = ClickableLabel(self.title_frame)
        self.App_logo.setGeometry(QtCore.QRect(30, 10, 30, 40))
        self.App_logo.setMaximumSize(QtCore.QSize(30, 50))
        self.App_logo.setText("")
        self.App_logo.setPixmap(QtGui.QPixmap(":/img/utils/images/KGM app logo1.png"))
        self.App_logo.setScaledContents(True)
        self.App_logo.setObjectName("App_logo")
        self.label_3 = QtWidgets.QLabel(self.title_frame)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.minimize_btn = QtWidgets.QPushButton(self.title_frame)
        self.minimize_btn.setGeometry(QtCore.QRect(790, 0, 31, 31))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.minimize_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/utils/images/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon)
        self.minimize_btn.setIconSize(QtCore.QSize(24, 24))
        self.minimize_btn.setObjectName("minimize_btn")
        self.Close_btn = QtWidgets.QPushButton(self.title_frame)
        self.Close_btn.setGeometry(QtCore.QRect(830, 0, 31, 30))
        self.Close_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.Close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/utils/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_btn.setIcon(icon1)
        self.Close_btn.setIconSize(QtCore.QSize(24, 20))
        self.Close_btn.setObjectName("Close_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 210, 281, 261))
        self.frame.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"border radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.currently_playing_logo = QtWidgets.QLabel(self.frame)
        self.currently_playing_logo.setGeometry(QtCore.QRect(30, 20, 31, 21))
        self.currently_playing_logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.currently_playing_logo.setText("")
        self.currently_playing_logo.setPixmap(QtGui.QPixmap(":/img/utils/images/current-music.png"))
        self.currently_playing_logo.setScaledContents(True)
        self.currently_playing_logo.setObjectName("currently_playing_logo")
        self.currently_playing = QtWidgets.QLabel(self.frame)
        self.currently_playing.setGeometry(QtCore.QRect(80, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.currently_playing.setFont(font)
        self.currently_playing.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.currently_playing.setObjectName("currently_playing")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(116, 212, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.Current_song_name = QtWidgets.QLabel(self.frame)
        self.Current_song_name.setGeometry(QtCore.QRect(30, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Current_song_name.setFont(font)
        self.Current_song_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.Current_song_name.setObjectName("Current_song_name")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(116, 212, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.Current_song_path = QtWidgets.QLabel(self.frame)
        self.Current_song_path.setGeometry(QtCore.QRect(30, 120, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Current_song_path.setFont(font)
        self.Current_song_path.setStyleSheet("color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.Current_song_path.setObjectName("Current_song_path")
        self.add_to_favourites_btn = QtWidgets.QPushButton(self.frame)
        self.add_to_favourites_btn.setGeometry(QtCore.QRect(50, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.add_to_favourites_btn.setFont(font)
        self.add_to_favourites_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(253, 124, 9);\n"
"raduis: 20px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/utils/images/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_favourites_btn.setIcon(icon2)
        self.add_to_favourites_btn.setObjectName("add_to_favourites_btn")
        self.add_to_playlist_btn = QtWidgets.QPushButton(self.frame)
        self.add_to_playlist_btn.setGeometry(QtCore.QRect(50, 200, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.add_to_playlist_btn.setFont(font)
        self.add_to_playlist_btn.setStyleSheet("background-color: rgb(253, 138, 32);\n"
"color: rgb(255, 255, 255);\n"
"raduis: 20px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/utils/images/music_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_playlist_btn.setIcon(icon3)
        self.add_to_playlist_btn.setObjectName("add_to_playlist_btn")
        self.volume_dial = QtWidgets.QDial(self.centralwidget)
        self.volume_dial.setGeometry(QtCore.QRect(240, 400, 131, 91))
        self.volume_dial.setMaximum(100)
        self.volume_dial.setProperty("value", 20)
        self.volume_dial.setWrapping(True)
        self.volume_dial.setNotchesVisible(True)
        self.volume_dial.setObjectName("volume_dial")
        self.volume_label = QtWidgets.QLabel(self.centralwidget)
        self.volume_label.setGeometry(QtCore.QRect(293, 425, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.volume_label.setFont(font)
        self.volume_label.setObjectName("volume_label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 480, 801, 51))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 222, 38))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgba(255, 255, 255, 50);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play_btn = QtWidgets.QPushButton(self.frame_3)
        self.play_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.play_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/utils/images/pase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_btn.setIcon(icon4)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout.addWidget(self.play_btn)
        self.pause_btn = QtWidgets.QPushButton(self.frame_3)
        self.pause_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.pause_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/utils/images/unpause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_btn.setIcon(icon5)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.frame_3)
        self.stop_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.stop_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/utils/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon6)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.prev_btn = QtWidgets.QPushButton(self.frame_3)
        self.prev_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.prev_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/utils/images/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev_btn.setIcon(icon7)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout.addWidget(self.prev_btn)
        self.next_btn = QtWidgets.QPushButton(self.frame_3)
        self.next_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.next_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/utils/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon8)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.loop_btn = QtWidgets.QPushButton(self.frame_3)
        self.loop_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(255, 255, 255, 130); \n"
"}")
        self.loop_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/utils/images/loop-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loop_btn.setIcon(icon9)
        self.loop_btn.setCheckable(True)
        self.loop_btn.setChecked(False)
        self.loop_btn.setObjectName("loop_btn")
        self.horizontalLayout.addWidget(self.loop_btn)
        self.shuffle_songs_btn = QtWidgets.QPushButton(self.frame_3)
        self.shuffle_songs_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,180);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(255, 255, 255, 130); \n"
"}")
        self.shuffle_songs_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/utils/images/play-random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_songs_btn.setIcon(icon10)
        self.shuffle_songs_btn.setCheckable(True)
        self.shuffle_songs_btn.setChecked(False)
        self.shuffle_songs_btn.setObjectName("shuffle_songs_btn")
        self.horizontalLayout.addWidget(self.shuffle_songs_btn)
        self.music_slider = QtWidgets.QSlider(self.frame_2)
        self.music_slider.setGeometry(QtCore.QRect(260, 20, 381, 21))
        self.music_slider.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid #999999;\n"
"    height: 15px;\n"
"    padding: 3px;\n"
"    background-color: rgba(56, 208, 255, 161);\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: rgb(253, 138, 32);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 5px;\n"
"    height:15px;\n"
"}")
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.time_lable = QtWidgets.QLabel(self.frame_2)
        self.time_lable.setGeometry(QtCore.QRect(660, 10, 131, 31))
        self.time_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.time_lable.setObjectName("time_lable")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(330, 70, 531, 351))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.stackedWidget.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
"border-radius: 10px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.song_list_label = QtWidgets.QLabel(self.page)
        self.song_list_label.setGeometry(QtCore.QRect(200, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.song_list_label.setFont(font)
        self.song_list_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(253, 138, 32);")
        self.song_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_list_label.setObjectName("song_list_label")
        self.add_songs_btn = QtWidgets.QPushButton(self.page)
        self.add_songs_btn.setEnabled(True)
        self.add_songs_btn.setGeometry(QtCore.QRect(390, 10, 41, 32))
        self.add_songs_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.add_songs_btn.setSizeIncrement(QtCore.QSize(30, 30))
        self.add_songs_btn.setBaseSize(QtCore.QSize(30, 30))
        self.add_songs_btn.setStyleSheet("cQPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.add_songs_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/utils/images/addFromLocal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_songs_btn.setIcon(icon11)
        self.add_songs_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_songs_btn.setObjectName("add_songs_btn")
        self.delete_selected_btn = QtWidgets.QPushButton(self.page)
        self.delete_selected_btn.setEnabled(True)
        self.delete_selected_btn.setGeometry(QtCore.QRect(430, 10, 41, 32))
        self.delete_selected_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_selected_btn.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_selected_btn.setBaseSize(QtCore.QSize(30, 30))
        self.delete_selected_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_selected_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/utils/images/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_selected_btn.setIcon(icon12)
        self.delete_selected_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_selected_btn.setObjectName("delete_selected_btn")
        self.delete_all_songs_btn = QtWidgets.QPushButton(self.page)
        self.delete_all_songs_btn.setEnabled(True)
        self.delete_all_songs_btn.setGeometry(QtCore.QRect(470, 10, 41, 32))
        self.delete_all_songs_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_all_songs_btn.setBaseSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_all_songs_btn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/utils/images/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_all_songs_btn.setIcon(icon13)
        self.delete_all_songs_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn.setObjectName("delete_all_songs_btn")
        self.song_listWidget = QtWidgets.QListWidget(self.page)
        self.song_listWidget.setGeometry(QtCore.QRect(20, 70, 491, 261))
        self.song_listWidget.setStyleSheet("background-color: rgba(230, 225, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(253, 138, 32);")
        self.song_listWidget.setObjectName("song_listWidget")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.playlist_Widget = QtWidgets.QListWidget(self.page_2)
        self.playlist_Widget.setGeometry(QtCore.QRect(20, 70, 491, 261))
        self.playlist_Widget.setStyleSheet("background-color: rgba(230, 225, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(253, 138, 32);")
        self.playlist_Widget.setObjectName("playlist_Widget")
        self.delete_selected_btn_2 = QtWidgets.QPushButton(self.page_2)
        self.delete_selected_btn_2.setEnabled(True)
        self.delete_selected_btn_2.setGeometry(QtCore.QRect(440, 10, 41, 32))
        self.delete_selected_btn_2.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_2.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_selected_btn_2.setBaseSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_selected_btn_2.setText("")
        self.delete_selected_btn_2.setIcon(icon12)
        self.delete_selected_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_2.setObjectName("delete_selected_btn_2")
        self.delete_all_songs_btn_2 = QtWidgets.QPushButton(self.page_2)
        self.delete_all_songs_btn_2.setEnabled(True)
        self.delete_all_songs_btn_2.setGeometry(QtCore.QRect(480, 10, 41, 32))
        self.delete_all_songs_btn_2.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_2.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_2.setBaseSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_all_songs_btn_2.setText("")
        self.delete_all_songs_btn_2.setIcon(icon13)
        self.delete_all_songs_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_2.setObjectName("delete_all_songs_btn_2")
        self.song_list_label_2 = QtWidgets.QLabel(self.page_2)
        self.song_list_label_2.setGeometry(QtCore.QRect(200, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.song_list_label_2.setFont(font)
        self.song_list_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(253, 138, 32);")
        self.song_list_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.song_list_label_2.setObjectName("song_list_label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.playlist_Widget_2 = QtWidgets.QListWidget(self.page_3)
        self.playlist_Widget_2.setGeometry(QtCore.QRect(20, 70, 491, 261))
        self.playlist_Widget_2.setStyleSheet("background-color: rgba(230, 225, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(253, 138, 32);")
        self.playlist_Widget_2.setObjectName("playlist_Widget_2")
        self.delete_selected_btn_3 = QtWidgets.QPushButton(self.page_3)
        self.delete_selected_btn_3.setEnabled(True)
        self.delete_selected_btn_3.setGeometry(QtCore.QRect(440, 10, 41, 32))
        self.delete_selected_btn_3.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_3.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_selected_btn_3.setBaseSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_selected_btn_3.setText("")
        self.delete_selected_btn_3.setIcon(icon12)
        self.delete_selected_btn_3.setIconSize(QtCore.QSize(30, 30))
        self.delete_selected_btn_3.setObjectName("delete_selected_btn_3")
        self.delete_all_songs_btn_3 = QtWidgets.QPushButton(self.page_3)
        self.delete_all_songs_btn_3.setEnabled(True)
        self.delete_all_songs_btn_3.setGeometry(QtCore.QRect(480, 10, 41, 32))
        self.delete_all_songs_btn_3.setMinimumSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_3.setSizeIncrement(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_3.setBaseSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,130);\n"
"}")
        self.delete_all_songs_btn_3.setText("")
        self.delete_all_songs_btn_3.setIcon(icon13)
        self.delete_all_songs_btn_3.setIconSize(QtCore.QSize(30, 30))
        self.delete_all_songs_btn_3.setObjectName("delete_all_songs_btn_3")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(180, 40, 21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/utils/images/like.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.favourite_song_list_lable = QtWidgets.QLabel(self.page_3)
        self.favourite_song_list_lable.setGeometry(QtCore.QRect(220, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.favourite_song_list_lable.setFont(font)
        self.favourite_song_list_lable.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(253, 138, 32);")
        self.favourite_song_list_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.favourite_song_list_lable.setObjectName("favourite_song_list_lable")
        self.stackedWidget.addWidget(self.page_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(360, 430, 471, 51))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.song_list_btn = QtWidgets.QPushButton(self.frame_4)
        self.song_list_btn.setGeometry(QtCore.QRect(10, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.song_list_btn.setFont(font)
        self.song_list_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(56, 208, 255, 161);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(56, 208, 255, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(30, 150, 200, 200); \n"
"}\n"
"")
        self.song_list_btn.setCheckable(True)
        self.song_list_btn.setObjectName("song_list_btn")
        self.playlist_btn = QtWidgets.QPushButton(self.frame_4)
        self.playlist_btn.setGeometry(QtCore.QRect(180, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.playlist_btn.setFont(font)
        self.playlist_btn.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(253, 138, 32, 161);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(254, 163, 29)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(30, 150, 200, 200); \n"
"}\n"
"")
        self.playlist_btn.setObjectName("playlist_btn")
        self.favourites_btn = QtWidgets.QPushButton(self.frame_4)
        self.favourites_btn.setGeometry(QtCore.QRect(350, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.favourites_btn.setFont(font)
        self.favourites_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 172, 146)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(30, 150, 200, 200); \n"
"}\n"
"\n"
"\n"
"")
        self.favourites_btn.setObjectName("favourites_btn")
        self.album_art_view = QtWidgets.QLabel(self.centralwidget)
        self.album_art_view.setGeometry(QtCore.QRect(91, 56, 161, 151))
        self.album_art_view.setText("")
        self.album_art_view.setPixmap(QtGui.QPixmap(":/img/utils/images/No-album-art.png"))
        self.album_art_view.setScaledContents(True)
        self.album_art_view.setObjectName("album_art_view")
        MusicApp.setCentralWidget(self.centralwidget)
        self.actionplay = QtWidgets.QAction(MusicApp)
        self.actionplay.setIcon(icon4)
        self.actionplay.setObjectName("actionplay")
        self.actionpause_unpause = QtWidgets.QAction(MusicApp)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/utils/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpause_unpause.setIcon(icon14)
        self.actionpause_unpause.setObjectName("actionpause_unpause")
        self.actionnext = QtWidgets.QAction(MusicApp)
        self.actionnext.setIcon(icon8)
        self.actionnext.setObjectName("actionnext")
        self.actionprevious = QtWidgets.QAction(MusicApp)
        self.actionprevious.setIcon(icon7)
        self.actionprevious.setObjectName("actionprevious")
        self.actionstop = QtWidgets.QAction(MusicApp)
        self.actionstop.setIcon(icon6)
        self.actionstop.setObjectName("actionstop")
        self.actionplayrandom = QtWidgets.QAction(MusicApp)
        self.actionplayrandom.setIcon(icon10)
        self.actionplayrandom.setObjectName("actionplayrandom")
        self.actionapp_logo_clicked = QtWidgets.QAction(MusicApp)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/utils/images/KGM app logo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionapp_logo_clicked.setIcon(icon15)
        self.actionapp_logo_clicked.setObjectName("actionapp_logo_clicked")

        self.retranslateUi(MusicApp)
        self.stackedWidget.setCurrentIndex(0)
        self.Close_btn.clicked.connect(MusicApp.close) # type: ignore
        self.minimize_btn.clicked.connect(MusicApp.showMinimized) # type: ignore
        self.volume_dial.valueChanged['int'].connect(self.volume_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MusicApp)

    def retranslateUi(self, MusicApp):
        _translate = QtCore.QCoreApplication.translate
        MusicApp.setWindowTitle(_translate("MusicApp", "KGM audio player"))
        self.label_3.setText(_translate("MusicApp", "KGM audio player"))
        self.currently_playing.setText(_translate("MusicApp", "Currently playing"))
        self.label_6.setText(_translate("MusicApp", "Name"))
        self.Current_song_name.setText(_translate("MusicApp", "Song name goes here"))
        self.label_7.setText(_translate("MusicApp", "Path"))
        self.Current_song_path.setText(_translate("MusicApp", "Song path goes here"))
        self.add_to_favourites_btn.setText(_translate("MusicApp", "Add to Favourites"))
        self.add_to_playlist_btn.setText(_translate("MusicApp", "Add to Playlist"))
        self.volume_label.setText(_translate("MusicApp", "20"))
        self.time_lable.setText(_translate("MusicApp", "00:00:00 / 00:00:00"))
        self.song_list_label.setText(_translate("MusicApp", "Song list"))
        self.song_list_label_2.setText(_translate("MusicApp", "Playlists"))
        self.favourite_song_list_lable.setText(_translate("MusicApp", "favourites list"))
        self.song_list_btn.setText(_translate("MusicApp", "Song list"))
        self.playlist_btn.setText(_translate("MusicApp", "playlist"))
        self.favourites_btn.setText(_translate("MusicApp", "favourites"))
        self.actionplay.setText(_translate("MusicApp", "play"))
        self.actionplay.setToolTip(_translate("MusicApp", "play audio"))
        self.actionplay.setShortcut(_translate("MusicApp", "Space"))
        self.actionpause_unpause.setText(_translate("MusicApp", "pause/unpause"))
        self.actionpause_unpause.setToolTip(_translate("MusicApp", "pause/ unpause "))
        self.actionpause_unpause.setShortcut(_translate("MusicApp", "Space"))
        self.actionnext.setText(_translate("MusicApp", "next"))
        self.actionnext.setToolTip(_translate("MusicApp", "next"))
        self.actionprevious.setText(_translate("MusicApp", "previous"))
        self.actionprevious.setToolTip(_translate("MusicApp", "previous"))
        self.actionstop.setText(_translate("MusicApp", "stop"))
        self.actionstop.setToolTip(_translate("MusicApp", "stop"))
        self.actionplayrandom.setText(_translate("MusicApp", "playrandom"))
        self.actionplayrandom.setToolTip(_translate("MusicApp", "randomize playback"))
        self.actionapp_logo_clicked.setText(_translate("MusicApp", "app-logo_clicked"))
        self.actionapp_logo_clicked.setToolTip(_translate("MusicApp", "About page"))
from clickablelabel import ClickableLabel
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MusicApp = QtWidgets.QMainWindow()
    ui = Ui_MusicApp()
    ui.setupUi(MusicApp)
    MusicApp.show()
    sys.exit(app.exec_())
